### ISSUE TITLE
Verzia 2018-07-22 sa neda nainstalovat

### ISSUE THREAD

**Issue by kapitan-iglu** [ibisek/vfrManual-android#1]
Po spusteni instalacie stianutej aplikacie 2018-07-22 instalator zahlasi:  `Aplikacia nebola nainstalovana. Zda sa, ze je balik poskodeny`. Sucastou release nie su checksumy, tak neviem overit integritu suboru apk.

Starsi release 2018-06-04 sa nainstaluje bez problemov.

Na Play Store neviem pomocou vyhladavania `VFR Manuál` aplikaciu najst, ani v telefone ani cez web (hoci vas odkaz funguje a Play aplikaciu naozaj pozna).

Co robim zle?

**Comment by ibisek** [comment]
Dneska jsme udelal aktualizaci (2019-03-28) - je to (nejspis) debugovaci APK (stejne jako ty predchozi); CZLovek (ten co to tam uploaduje) by sem (a na Play) mel behem zitrka hodit podepsanou verzi, az tu bude, zkuste ji.

Na Play-u zkuste hledat "VFR Manual" bez dlouheho "a". Treba to pomuze. Nebo treba jen "VFR". Kdyz se ted divam, tak je to tam pojmenovane jako "VFR Manual CZ".. to CZ bychom mohli asi odstranit.

**Comment by ibisek** [comment]
[(v1.9)](https://github.com/ibisek/vfrManual-android/releases/tag/v1.9) se zatim zda byt plne funkcni.

**Comment by kapitan-iglu** [comment]
Aplikaciu som si nainstalovat uspesne z Play Store. Stiahnute subory apk  v1.9 a v1.8 sa mi lokalne nepodarilo nainstalovat, rovnaka chyba `Zda sa, ze je balik poskodeny`. Nevadi, hlavne, ze funguje Play.
