### ISSUE TITLE
Slovenske data

### ISSUE THREAD

**Issue by kapitan-iglu** [ibisek/vfrManual-android#2]
Zdravim,
z kade beriete data pre Slovensko? Z OpenFlightMaps? Ak ano, mate nejake informacie, z kade oni beru podklady a ake doverihodne su? Priamo z [LPS.sk](https://aim.lps.sk/web/)?

Ako casto updatujete data pre Slovensko? U nas sa frekvencie menia snad [kazdy mesiac](https://aim.lps.sk/web/index.php?fn=151&lng=sk&param=30&sess=TRThUYSK67iUALNZAs0tSuq3BBJjvNqeGHDBGJAF)...

**Comment by ibisek** [comment]
Jo, SK je ciste z OpenFlightMaps. Nekdo navrhoval brat to z vaseho "RLP", ale je tam potreba se prihlasit a co jsem se dostal k informacim, tak tam byly jen PDFka, nic, co by slo nejak snadno parsovat. Nebo se to zmenilo? Kdyby byl pouzitelny zdroj, tak to rad pridam!

Aktualizace byly loni delany pokazde, kdyz jsem si vsiml, ze se na http://lis.rlp.cz/vfrmanual/ objevila nova verze, ke konci leta uz ne tak casto a od konce plachtarske sezony uz jsem to neresil -> bylo by dobre to zautomatizovat, jak jsem psal v issue #3.

**Comment by ibisek** [comment]
Obrazky letist budou (casem) ze zdroje [Letecká informačná služba Slovenskej republiky](https://aim.lps.sk/web/). Ale nejsou tam UL plochy, treba nekdo casem doporuci kde brat i ty..

**Comment by kapitan-iglu** [comment]
Slovenska LPS zaviedla nedavno [VFR Manual ](https://aim.lps.sk/web/index.php?fn=207&lng=en&sess=PZ2PzIoVVzv4eUkp9Uiijf0SMZQfhor1ICECDGGF) ale, bohuzial, opat strojovo necitatelne PDF subory. Podla rozhovoru so zamestnancom LPS su nakloneny poskytnut aj data vo formate AIXM, mozno sa to teda casom zmeni... Pokusim sa zistit za akych podmienok a na ake ucely.

LPS poskytuje len overene a zarucene informacie. Preto tam vela ploch chyba. Zatial neviem, z kade by sa neoverene data k UL plocham dali ziskat (v elektronickej podobe).

Otazna je aj motivacia robit free alternativu k aplikacii [Databaze Letist](http://www.aerobaze.cz/app/)...
