### ISSUE TITLE
Oddelit data od aplikacie

### ISSUE THREAD

**Issue by kapitan-iglu** [ibisek/vfrManual-android#3]
Rozmyslali ste nad moznostou oddelit data od samotnej aplikacie? Ak som to spravne pochopil, tak teraz su data integralnou sucastou aplikacie a pri ich zmene sa musi cela aplikacia prekompilovat a updatnut.

Ak by boli data oddelene od aplikacie, tak by si ich mohla automaticky stiahnut (po spusteni) napr. z githubu a ulozit do telefonu. Na github by sa mohli data dostavat automatizovane: CI/CRON/... by spustal openflightmaps.py/html2json.py a vysledky pushoval. Tym by sa zabezpecila ich neustala aktualnost.

**Comment by ibisek** [comment]
Ahoj! Ano, premyslel jsem nad tim, ale nenapadlo me, ze by data sly stahovat primo z githubu - porad jsem uvazoval o tom, kde to hostovat atd.. Takze je to prakticky a dobry napad.

Ohledne automatickeho stahovani a updatovani - jde tu na githubu udelat crontask, ktery by spoustel skript? Kde by ten skript bezel? Prepokladam, ze mas na mysli skript na nejakem externim serveru, ktery by to stahoval, tam prechroustal a pak sem pushoval.. nebo nejak jinak? (Problem je ten server).

Dalsi vec je, ze by pak aplikace potrebovala Network permission (cemuz jsem se chtel vyhnout, ale nakonec tam prijde, protoze uz se pracuje i na zobrazeni a aktualizaci aktivnich prostoru z AIS view.. takze by to pak muselo kontrolovat neco (release? / nejaky json na githubu) a podle toho to stahovat. A navic idealne jen zmenene soubory.. (podle hashe).. takze spousta prace. (mam ted hodne prace s OGN krabickami, prakticky je to celkem hukot, takze snad behem sezony).

Nebo.. nechces to udelat? :)

**Comment by kapitan-iglu** [comment]
1. Cronjob nemusi bezat na githube. Moze bezat aj doma na domacom PC alebo ho spusti niekto raz za cas rucne. Vysledne subory s datami by sa potom pushli na github do (najlepsie separatneho) repozitara. Cize v podstate to iste co robis teraz, akurat by vysledkom nebola prekompilovana apk ale commit na github.
2. Network permission ma uz hadam kazda aplikacia. Ak bude v popise aplikacie/priamo v aplikacii vysvetlene, ze to je len kvoli automatickym updatom dat tak by s tym nemal mat uzivatel problem. 
3. Stahovat len zmeny by sa dalo napr. pomocou verziovacieho systemu (git/svn) priamo z aplikacie. Pri update by sa stiahli len zmeny medzi HEAD a lokalnou reviziou dat v telefone. Ci existuje kniznica implementujuca git/svn aj pre android aplikacie neviem. 
4. Android vyvojar nie som, inak by som rovno poslal PR :)

**Comment by ibisek** [comment]
Nova verze, na ktere sukin prave pracuje to uz bude mit (teda ma, ale zatim to jeste neni venku)
A inverzni rezim (tmave pozadi) je tam uz taky.
Navic pribylo i nastaveni jednotek vysky, takze uz se nebudeme hadat.
